/**
 * Deployment script for EventTicketNFT.
 *
 * On the local Hardhat network this also seeds three demo events so the
 * frontend has content to render out of the box.
 *
 * It always writes the deployed address + ABI to:
 *    frontend/src/utils/contract.js
 * so the frontend picks up changes automatically after a fresh deploy.
 */
const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

// The contract now stores ONLY a metadata URI on chain. For the local
// demo seed we inline the full JSON metadata as a base64 data URL so the
// frontend renders the demo events fully (banner, name, description,
// category, section labels) without depending on Pinata or a local IPFS
// daemon being up.
function demoMetadata(ev) {
  const doc = {
    name: ev.name,
    description: ev.description,
    category: ev.category,
    image: ev.image,
    attributes: [{ trait_type: "Category", value: ev.category }],
    sections: ev.sections.map((s) => ({ name: s.name })),
  };
  return "data:application/json;base64," + Buffer.from(JSON.stringify(doc)).toString("base64");
}

const DEMO_EVENTS = [
  {
    name: "Indie Night Live",
    category: "Music",
    description:
      "An intimate evening of local indie bands taking over the rooftop stage. Expect three sets, a guest DJ between acts, and street-food trucks downstairs.",
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&w=1200&q=80",
    daysAhead: 14,
    royaltyBps: 800,
    maxPerBuyer: 4,
    sections: [
      { name: "Front Row", priceEth: "0.12", maxTickets: 20 },
      { name: "Standing",  priceEth: "0.05", maxTickets: 60 },
    ],
  },
  {
    name: "Blockchain & You Conference",
    category: "Conference",
    description:
      "A full-day conference covering real-world smart-contract design, scaling strategies, and security best practices, with workshops and live demos.",
    image: "https://images.unsplash.com/photo-1591115765373-5207764f72e7?auto=format&fit=crop&w=1200&q=80",
    daysAhead: 21,
    royaltyBps: 500,
    maxPerBuyer: 2,
    sections: [
      { name: "Speaker Pass", priceEth: "0.35", maxTickets: 30 },
      { name: "General",      priceEth: "0.12", maxTickets: 120 },
    ],
  },
  {
    name: "Theatre Night — A Midsummer Script Dream",
    category: "Theatre",
    description:
      "A witty modern retelling of Shakespeare's classic performed by the city's resident troupe. Runtime ~110 minutes with a 15-minute interval.",
    image: "https://images.unsplash.com/photo-1503095396549-807759245b35?auto=format&fit=crop&w=1200&q=80",
    daysAhead: 30,
    royaltyBps: 1000,
    maxPerBuyer: 6,
    sections: [
      { name: "Orchestra", priceEth: "0.08", maxTickets: 20 },
      { name: "Balcony",   priceEth: "0.03", maxTickets: 40 },
    ],
  },
];

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  const network = hre.network.name;

  console.log("\n════════════════════════════════════════════════════════════");
  console.log("  EventTicketNFT — Deployment");
  console.log("════════════════════════════════════════════════════════════");
  console.log(`  Network : ${network}`);
  console.log(`  Deployer: ${deployer.address}`);
  console.log(
    `  Balance : ${hre.ethers.formatEther(
      await hre.ethers.provider.getBalance(deployer.address)
    )} ETH`
  );

  const Factory = await hre.ethers.getContractFactory("EventTicketNFT");
  const contract = await Factory.deploy();
  await contract.waitForDeployment();
  const contractAddress = await contract.getAddress();

  console.log("\n  Contract: EventTicketNFT");
  console.log(`  Address : ${contractAddress}`);

  // Seed demo events on local networks only.
  if (network === "localhost" || network === "hardhat") {
    console.log("\n  Seeding demo events...");
    const now = Math.floor(Date.now() / 1000);
    for (const ev of DEMO_EVENTS) {
      const sections = ev.sections.map((s) => ({
        priceWei: hre.ethers.parseEther(s.priceEth),
        maxTickets: s.maxTickets,
      }));
      const metadataURI = demoMetadata(ev);
      const tx = await contract.createEvent(
        metadataURI,
        now + ev.daysAhead * 24 * 60 * 60,
        ev.royaltyBps,
        ev.maxPerBuyer,
        sections
      );
      await tx.wait();
      const summary = ev.sections
        .map((s) => `${s.name} ${s.priceEth}ETH ×${s.maxTickets}`)
        .join(", ");
      console.log(`    ✓ ${ev.name} — ${summary}`);
    }
  }

  // Persist address + ABI to the frontend.
  const artifact = await hre.artifacts.readArtifact("EventTicketNFT");
  const frontendConfigDir = path.resolve(__dirname, "../frontend/src/utils");
  if (!fs.existsSync(frontendConfigDir)) {
    fs.mkdirSync(frontendConfigDir, { recursive: true });
  }

  const chainId = hre.network.config.chainId || 31337;
  const contractJs = `// Auto-generated by scripts/deploy.js — do not edit manually.
export const CONTRACT_ADDRESS = "${contractAddress}";
export const CHAIN_ID = ${chainId};
export const NETWORK_NAME = "${network === "hardhat" ? "Hardhat Local" : network}";
export const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};
`;
  fs.writeFileSync(path.join(frontendConfigDir, "contract.js"), contractJs);

  console.log("\n  Frontend config written → frontend/src/utils/contract.js");
  console.log("════════════════════════════════════════════════════════════\n");
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
