/**
 * Deployment script for EventTicketNFT.
 *
 * On the local Hardhat network this also seeds three demo events so the
 * frontend has content to render out of the box.
 *
 * It always writes the deployed address + ABI to:
 *    frontend/src/utils/contract.js
 * so the frontend picks up changes automatically after a fresh deploy.
 */
const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

const DEMO_EVENTS = [
  {
    name: "Indie Night Live",
    category: "Music",
    metadataURI: "ipfs://bafybeigindiecid",
    daysAhead: 14,
    priceEth: "0.05",
    maxTickets: 80,
    royaltyBps: 800, // 8%
    maxPerBuyer: 4,
  },
  {
    name: "Blockchain & You Conference",
    category: "Conference",
    metadataURI: "ipfs://bafybeigconfcid",
    daysAhead: 21,
    priceEth: "0.12",
    maxTickets: 150,
    royaltyBps: 500, // 5%
    maxPerBuyer: 2,
  },
  {
    name: "Theatre Night — A Midsummer Script Dream",
    category: "Theatre",
    metadataURI: "ipfs://bafybeigtheatercid",
    daysAhead: 30,
    priceEth: "0.03",
    maxTickets: 60,
    royaltyBps: 1000, // 10%
    maxPerBuyer: 6,
  },
];

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  const network = hre.network.name;

  console.log("\n════════════════════════════════════════════════════════════");
  console.log("  EventTicketNFT — Deployment");
  console.log("════════════════════════════════════════════════════════════");
  console.log(`  Network : ${network}`);
  console.log(`  Deployer: ${deployer.address}`);
  console.log(
    `  Balance : ${hre.ethers.formatEther(
      await hre.ethers.provider.getBalance(deployer.address)
    )} ETH`
  );

  const Factory = await hre.ethers.getContractFactory("EventTicketNFT");
  const contract = await Factory.deploy();
  await contract.waitForDeployment();
  const contractAddress = await contract.getAddress();

  console.log("\n  Contract: EventTicketNFT");
  console.log(`  Address : ${contractAddress}`);

  // Seed demo events on local networks only.
  if (network === "localhost" || network === "hardhat") {
    console.log("\n  Seeding demo events...");
    const now = Math.floor(Date.now() / 1000);
    for (const ev of DEMO_EVENTS) {
      const tx = await contract.createEvent(
        ev.name,
        ev.category,
        ev.metadataURI,
        now + ev.daysAhead * 24 * 60 * 60,
        hre.ethers.parseEther(ev.priceEth),
        ev.maxTickets,
        ev.royaltyBps,
        ev.maxPerBuyer
      );
      await tx.wait();
      console.log(`    ✓ ${ev.name} (${ev.priceEth} ETH, ${ev.maxTickets} tickets)`);
    }
  }

  // Persist address + ABI to the frontend.
  const artifact = await hre.artifacts.readArtifact("EventTicketNFT");
  const frontendConfigDir = path.resolve(__dirname, "../frontend/src/utils");
  if (!fs.existsSync(frontendConfigDir)) {
    fs.mkdirSync(frontendConfigDir, { recursive: true });
  }

  const chainId = hre.network.config.chainId || 31337;
  const contractJs = `// Auto-generated by scripts/deploy.js — do not edit manually.
export const CONTRACT_ADDRESS = "${contractAddress}";
export const CHAIN_ID = ${chainId};
export const NETWORK_NAME = "${network === "hardhat" ? "Hardhat Local" : network}";
export const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};
`;
  fs.writeFileSync(path.join(frontendConfigDir, "contract.js"), contractJs);

  console.log("\n  Frontend config written → frontend/src/utils/contract.js");
  console.log("════════════════════════════════════════════════════════════\n");
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
